---
- name: remove the iis web service
  hosts: windows

  tasks:
    - name: stop iis service
      win_service:
        name: W3Svc
        state: absent

    - name: remove iis
      win_feature:
        name: Web-Server
        state: absent
