---
- hosts: windows_new
  tasks:
    - name: Check Ansible version
      win_shell: ansible --version
      register: ansibleVersion

    - name: Print version
      debug:
        msg: "Ansible Version: {{ ansibleVersion.stdout }}"