---
- name: Check status of IIS services
  hosts: windows_new #the host group from my inventory

# Example that prints the loopback address and gateway for each host
  tasks:
  - name: Info variables
    debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
    when: inventory_hostname is defined

  - name: Info variables II
    debug:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
    when: ansible_default_ipv4.gateway is defined

  - name: Info Uptime
    shell: /usr/bin/uptime
    register: result

  - name: Info Verbosity var result
    debug:
      var: result
      verbosity: 2

  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
      verbosity: 4