---
- name: Check status of IIS services
  hosts: windows_new #the host group from my inventory

# task lists
  tasks:
  - name: Status IIS service
    win_service:
      name: W3Svc
      register: service_info

  - name: "print status of service"
    debug: 
      var: service_info
      msg: "status {{ service_info }}"